files:
  - source: /bukkit/src/main/resources/bukkit/messages.yml
    translation: /locales/bukkit/messages_%two_letters_code%.yml
  - source: /bungeecord/src/main/resources/bungee/messages.yml
    translation: /locales/bungeecord/messages_%two_letters_code%.yml