name: Parties
main: com.alessiodp.parties.Parties
version: 1.6.1
description: Party manager for minecraft servers
softdepend: [Vault, DeluxeChat, PlaceholderAPI, Dynmap]
permissions:
    parties.sendmessage:
        description: Command /p
    parties.help:
        description: Command /party
    parties.create:
        description: Command /party create
    parties.leave:
        description: Command /party leave
    parties.ignore:
        description: Command /party ignore
    parties.accept:
        description: Command /party accept
    parties.deny:
        description: Command /party deny
    parties.join:
        description: Command /party join
    parties.join.others:
        description: Command /party join in other parties
    parties.password:
        description: Command /party password
    parties.info:
        description: Command /party info
    parties.info.others:
        description: Command /party info on other parties
    parties.members:
        description: Command /party members
    parties.members.others:
        description: Command /party members on other parties
    parties.invite:
        description: Command /party invite
    parties.chat:
        description: Command /party chat
    parties.list:
        description: Command /party list
    parties.home:
        description: Command /party home
    parties.home.others:
        description: Command /party home on other homes
    parties.sethome:
        description: Command /party sethome
    parties.desc:
        description: Command /party desc
    parties.motd:
        description: Command /party motd
    parties.prefix:
        description: Command /party prefix
    parties.suffix:
        description: Command /party suffix
    parties.kick:
        description: Command /party kick
    parties.kick.others:
        description: Command /party kick on other players
    parties.rank:
        description: Command /party rank
    parties.rank.others:
        description: Command /party rank on other players
    parties.claim:
        description: Command /party claim with GriefPrevention
    parties.admin.vaultbypass:
        description: Bypass vault party commands
    parties.admin.delete:
        description: Command /party delete
    parties.admin.delete.silent:
        description: Command /party delete with silent
    parties.admin.rename:
        description: Command /party rename
    parties.admin.spy:
        description: Command /party spy
    parties.admin.reload:
        description: Command /party reload
    parties.admin.updates:
        description: Send message if available new version
    parties.admin.migrate:
        description: Command /party migrate
    parties.user.*:
        default: op
        description: Can use party commands
        children:
          parties.sendmessage: true
          parties.help: true
          parties.create: true
          parties.join: true
          parties.password: true
          parties.accept: true
          parties.deny: true
          parties.ignore: true
          parties.leave: true
          parties.info: true
          parties.info.others: true
          parties.members: true
          parties.members.others: true
          parties.home: true
          parties.sethome: true
          parties.desc: true
          parties.motd: true
          parties.chat: true
          parties.list: true
          parties.invite: true
          parties.prefix: true
          parties.suffix: true
          parties.kick: true
          parties.rank: true
          parties.claim: true
    parties.admin.*:
        default: op
        description: Can use all party commands
        children:
          parties.user.*: true
          parties.rank.others: true
          parties.home.others: true
          parties.join.others: true
          parties.kick.others: true
          parties.admin.vaultbypass: true
          parties.admin.delete: true
          parties.admin.delete.silent: true
          parties.admin.rename: true
          parties.admin.spy: true
          parties.admin.reload: true
          parties.admin.updates: true
          parties.admin.migrate: true