name: ${plugin.name}
description: ${plugin.description}
author: ${plugin.author}
website: ${plugin.website}
version: ${plugin.version}
main: com.alessiodp.parties.bukkit.bootstrap.BukkitPartiesBootstrap
api-version: 1.13
softdepend: [CrackShot, Dynmap, PlaceholderAPI, ProtocolLib, SkillAPI, Vault]
permissions:
  parties.accept:
    description: Allow access to /party accept
  parties.chat:
    description: Allow access to /party chat
  parties.claim:
    description: Allow access to /party claim with GriefPrevention
  parties.color:
    description: Allow access to /party color
  parties.create:
    description: Allow access to /party create
  parties.deny:
    description: Allow access to /party deny
  parties.desc:
    description: Allow access to /party desc
  parties.help:
    description: Allow access to /party or /party help
  parties.home:
    description: Allow access to /party home
  parties.home.others:
    description: Allow access to /party home on other homes
  parties.ignore:
    description: Allow access to /party ignore
  parties.info:
    description: Allow access to /party info
  parties.info.others:
    description: Allow access to /party info on other parties
  parties.invite:
    description: Allow access to /party invite
  parties.join:
    description: Allow access to /party join
  parties.join.bypass:
    description: Allow access to /party join in other parties without insert the password
  parties.joindefault:
    description: Join into the default party
  parties.kick:
    description: Allow access to /party kick
  parties.kick.others:
    description: Allow access to /party kick on other players
  parties.leave:
    description: Allow access to /party leave
  parties.list:
    description: Allow access to /party list
  parties.motd:
    description: Allow access to /party motd
  parties.notify:
    description: Allow access to /party notify
  parties.password:
    description: Allow access to /party password
  parties.rank:
    description: Allow access to /party rank
  parties.rank.others:
    description: Allow access to /party rank on other players
  parties.rename:
    description: Allow access to /party rename
  parties.rename.others:
    description: Allow access to /party rename on other parties
  parties.sendmessage:
    description: Allow access to /p
  parties.sethome:
    description: Allow access to /party sethome
  parties.teleport:
    description: Allow access to /party teleport
  parties.admin.create.fixed:
    description: Allow access to /party create party fixed
  parties.admin.delete:
    description: Allow access to /party delete
  parties.admin.delete.silent:
    description: Allow access to /party delete with silent
  parties.admin.joindefault.bypass:
    description: Bypass the default join
  parties.admin.migrate:
    description: Allow access to /party migrate
  parties.admin.rankbypass:
    description: Bypass rank restrictions
  parties.admin.reload:
    description: Allow access to /party reload
  parties.admin.spy:
    description: Allow access to /party spy
  parties.admin.updates:
    description: Send a message if there is an update
  parties.admin.vaultbypass:
    description: Bypass commands that have a price
  parties.user.*:
    default: op
    description: Can use normal party commands
    children:
      parties.accept: true
      parties.chat: true
      parties.claim: true
      parties.color: true
      parties.create: true
      parties.deny: true
      parties.desc: true
      parties.help: true
      parties.home: true
      parties.ignore: true
      parties.info: true
      parties.info.others: true
      parties.invite: true
      parties.join: true
      parties.joindefault: true
      parties.kick: true
      parties.leave: true
      parties.list: true
      parties.motd: true
      parties.notify: true
      parties.password: true
      parties.rank: true
      parties.rename: true
      parties.sendmessage: true
      parties.sethome: true
      parties.teleport: true
  parties.admin.*:
    default: op
    description: Can use all party commands
    children:
      parties.user.*: true
      parties.home.others: true
      parties.join.others: true
      parties.kick.others: true
      parties.rank.others: true
      parties.rename.others: true
      parties.admin.delete: true
      parties.admin.delete.silent: true
      parties.admin.fixed: true
      parties.admin.joindefault.bypass: true
      parties.admin.migrate: true
      parties.admin.rankbypass: true
      parties.admin.reload: true
      parties.admin.spy: true
      parties.admin.updates: true
      parties.admin.vaultbypass: true
