# 
# Parties configuration file
#
# For a better configuration:
# - Use Notepad++
#   - View -> Show White Space and TAB (Active)
#   - Don't use arrows, but spaces
# - Set format (syntax) editor to YAML
#
follow-party:
    # When player join in a server, whole party follow him
    enable: false
    # Needed rank to be followed by the party (0 = all ranks)
    needed-rank: 0
    # Minimum rank of player who can follow the party (0 = all ranks)
    minimum-rank-to-follow: 0
    # List of servers which use follow-party ('*' = all servers)
    list-server:
    - hub
    - lobby
dont-edit-this:
    config-version: 2